package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Consumer generated by hbm2java
 */
public class Consumer extends User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -271559155257575503L;
	private String wazaBucks;
	private String photo;
	
	public Consumer() {
	}

	public Consumer(String wazaBucks, String photo) {
		this.wazaBucks = wazaBucks;
		this.photo = photo;
	}

	public String getWazaBucks() {
		return this.wazaBucks;
	}

	public void setWazaBucks(String wazaBucks) {
		this.wazaBucks = wazaBucks;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
