package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * CookedItemIngredients generated by hbm2java
 */
public class CookedItemIngredients implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2208231342177659725L;
	private Long ingredientId;
	private Long cookedItemId;
	private int quantity;

	public CookedItemIngredients() {
	}

	public CookedItemIngredients(Long cookedItemId, int quantity) {
		this.cookedItemId = cookedItemId;
		this.quantity = quantity;
	}

	public Long getIngredientId() {
		return this.ingredientId;
	}

	public void setIngredientId(Long ingredientId) {
		this.ingredientId = ingredientId;
	}

	public Long getCookedItemId() {
		return this.cookedItemId;
	}

	public void setCookedItemId(Long cookedItemId) {
		this.cookedItemId = cookedItemId;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
