package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * CookedItem generated by hbm2java
 */
public class CookedItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3057465223200900896L;
	private Long itemId;
	private Long userId;
	private String title;
	private String description;
	private String categoryId;
	private String subCategoryId;
	private String imagePath;
	private String price;
	private String upvote;
	private String downvote;
	
	private String wazaBucks;
	private String ingredients;
	private String quantity;

	public CookedItem() {
	}

	public CookedItem(Long userId, String title) {
		this.userId = userId;
		this.title = title;
	}

	public CookedItem(Long userId, String title, String description,
			String categoryId, String subCategoryId, String imagePath,
			String price, String upvote, String downvote, String wazaBucks,
			String ingredients, String quantity) {
		this.userId = userId;
		this.title = title;
		this.description = description;
		this.categoryId = categoryId;
		this.subCategoryId = subCategoryId;
		this.imagePath = imagePath;
		this.price = price;
		this.upvote = upvote;
		this.downvote = downvote;
		this.wazaBucks = wazaBucks;
		this.ingredients = ingredients;
		this.quantity = quantity;
	}

	public Long getItemId() {
		return this.itemId;
	}

	public void setItemId(Long id) {
		this.itemId = id;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(String categoryId) {
		this.categoryId = categoryId;
	}

	public String getSubCategoryId() {
		return this.subCategoryId;
	}

	public void setSubCategoryId(String subCategoryId) {
		this.subCategoryId = subCategoryId;
	}

	public String getImagePath() {
		return this.imagePath;
	}

	public void setImagePath(String imagePath) {
		this.imagePath = imagePath;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getUpvote() {
		return this.upvote;
	}

	public void setUpvote(String upvote) {
		this.upvote = upvote;
	}

	public String getDownvote() {
		return this.downvote;
	}

	public void setDownvote(String downvote) {
		this.downvote = downvote;
	}
	
	public String getWazaBucks() {
		return wazaBucks;
	}

	public void setWazaBucks(String wazaBucks) {
		this.wazaBucks = wazaBucks;
	}

	public String getIngredients() {
		return ingredients;
	}

	public void setIngredients(String ingredients) {
		this.ingredients = ingredients;
	}

	public String getQuantity() {
		return quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	

}
