package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * Ingredient generated by hbm2java
 */
public class Ingredient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7143908762168065152L;
	private Long id;
	private String ingredientName;
	private String energy;

	public Ingredient() {
	}

	public Ingredient(String ingredientName, String energy) {
		this.ingredientName = ingredientName;
		this.energy = energy;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getIngredientName() {
		return this.ingredientName;
	}

	public void setIngredientName(String ingredientName) {
		this.ingredientName = ingredientName;
	}

	public String getEnergy() {
		return this.energy;
	}

	public void setEnergy(String energy) {
		this.energy = energy;
	}

}
