package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * UserFoodSchedule generated by hbm2java
 */
public class UserFoodSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4333188983769992222L;
	private Long id;
	private Long cookedItemId;
	private Long userId;
	private Date date;
	private String quantity;
	private Long locationId;
	private String price;
	private String wazaBucks;
	
	public UserFoodSchedule() {
	}

	public UserFoodSchedule(Long cookedItemId, Long userId) {
		this.cookedItemId = cookedItemId;
		this.userId = userId;
	}

	public UserFoodSchedule(Long cookedItemId, Long userId, Date date,
			String quantity, Long locationId, String price, String wazaBucks) {
		this.cookedItemId = cookedItemId;
		this.userId = userId;
		this.date = date;
		this.quantity = quantity;
		this.locationId = locationId;
		this.price = price;
		this.wazaBucks = wazaBucks;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Long getCookedItemId() {
		return this.cookedItemId;
	}

	public void setCookedItemId(Long cookedItemId) {
		this.cookedItemId = cookedItemId;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public Long getLocationId() {
		return locationId;
	}

	public void setLocationId(Long locationId) {
		this.locationId = locationId;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getWazaBucks() {
		return wazaBucks;
	}

	public void setWazaBucks(String wazaBucks) {
		this.wazaBucks = wazaBucks;
	}
	
}
