package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.xml.bind.annotation.XmlRootElement;

/**
 * UserFoodSchedule generated by hbm2java
 */
@XmlRootElement
public class UserFoodSchedule implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4333188983769992222L;
	private Long scheduleId;
	private CookedItem foodItem;
	private Long userId;
	private Date date;
	private String quantity;
	private Location location;
	private String price;
	private String wazaBucks;
	
	public UserFoodSchedule() {
	}

	public UserFoodSchedule(CookedItem foodItem, Long userId) {
		this.foodItem = foodItem;
		this.userId = userId;
	}

	public UserFoodSchedule(CookedItem foodItem, Long userId, Date date,
			String quantity, Location location, String price, String wazaBucks) {
		this.foodItem = foodItem;
		this.userId = userId;
		this.date = date;
		this.quantity = quantity;
		this.location = location;
		this.price = price;
		this.wazaBucks = wazaBucks;
	}

	public Long getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(Long scheduleId) {
		this.scheduleId = scheduleId;
	}

	public CookedItem getFoodItem() {
		return this.foodItem;
	}

	public void setFoodItem(CookedItem foodItem) {
		this.foodItem = foodItem;
	}

	public Long getUserId() {
		return this.userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}


	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public String getQuantity() {
		return this.quantity;
	}

	public void setQuantity(String quantity) {
		this.quantity = quantity;
	}

	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public String getPrice() {
		return price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getWazaBucks() {
		return wazaBucks;
	}

	public void setWazaBucks(String wazaBucks) {
		this.wazaBucks = wazaBucks;
	}
	
}
