package com.inncrewin.waza.hibernate;

// Generated Sep 16, 2013 4:18:06 PM by Hibernate Tools 3.4.0.CR1

/**
 * WazaCredits generated by hbm2java
 */
public class WazaCredits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1414591802436955908L;
	private Long id;
	private String couponType;
	private String wazaCreditsPerType;

	public WazaCredits() {
	}

	public WazaCredits(String couponType, String wazaCreditsPerType) {
		this.couponType = couponType;
		this.wazaCreditsPerType = wazaCreditsPerType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCouponType() {
		return this.couponType;
	}

	public void setCouponType(String couponType) {
		this.couponType = couponType;
	}

	public String getWazaCreditsPerType() {
		return this.wazaCreditsPerType;
	}

	public void setWazaCreditsPerType(String wazaCreditsPerType) {
		this.wazaCreditsPerType = wazaCreditsPerType;
	}

}
